url: https://san-da.github.io/
baseurl: https://y7kim.github.io

# Site settings
title: 산다 온라인 심리상담소
email: sanda.counselor@gmail.com
description: 산다의 온라인 심리상담소입니다


# Team names, titles and social links
people:
- name: Moon
  pic: 1
  position: 변호사(Lawyer)
 
- name: San-da
  pic: 2
  position: 심리상담사(Counselor)


- name: SY
  pic: 3
  position: 디자이너(Designer)
  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/san-da/

# Build settings
markdown: kramdown
permalink: pretty